version: '3'

services:
  app:
    build:
      context: ./
    container_name: music_app
    ports:
      - "127.0.0.1:6196:80"
    depends_on:
      - redis
    env_file:
      - .env
    restart: always
    networks:
      default:

  redis:
    image: redis:alpine
    container_name: music_redis
    restart: always
    networks:
      default:
