"""add lyrics

Revision ID: 17fe2d6d6748
Revises: 8bae8ce28b61
Create Date: 2025-01-30 11:11:36.787935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fe2d6d6748'
down_revision = '8bae8ce28b61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('lyrics', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'lyrics')
    # ### end Alembic commands ###
