"""new song fields

Revision ID: 8bae8ce28b61
Revises: 3d7e87db8342
Create Date: 2025-01-30 11:01:10.610975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8bae8ce28b61'
down_revision = '3d7e87db8342'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('prompt', sa.String(), server_default='', nullable=False))
    op.add_column('songs', sa.Column('with_voice', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('songs', 'status',
               existing_type=postgresql.ENUM('finished', 'queued', 'error', name='songstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'status',
               existing_type=postgresql.ENUM('finished', 'queued', 'error', name='songstatus'),
               nullable=False)
    op.drop_column('songs', 'with_voice')
    op.drop_column('songs', 'prompt')
    # ### end Alembic commands ###
